excel_source_path = "./iiko_reports/"
excel_target_path = "./excel_files_generated/"
xml_target_path = "./xml_files_generated/"

date_cell = "A3"
restaurant_cell = "A6"
cooking_place_col = "B"
cooking_place_cell = "B6"
dishes_group_col = "C"
payment_type_col = "C"
dishes_col = "D"
units_col = "E"
dish_code_col = "F"
quantity_col = "G"
sum_col = "H"
cost_col = "I"
percent_col = "J"
sum_without_excise_col = "L"
sum_without_vat_col = "M"
price_col = "N"
uktzed_col = "O"
document_text_cell = "A4"
document_number_cell = "B4"
place = "lan"
version="2.1.0"

new_restaurant_cell = "C4"
